# Generated by Django 2.2.9 on 2020-01-13 22:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministro',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
