# Generated by Django 2.2.9 on 2020-01-14 00:26

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suministros", "0003_auto_20200113_2325"),
    ]

    operations = [
        migrations.AddField(
            model_name="suministro",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["title", "municipality"]
            ),
        ),
    ]
