# Generated by Django 2.2.9 on 2020-01-15 23:01

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suministros", "0004_suministro_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suministro",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=255,
                populate_from=["title", "municipality"],
            ),
        ),
    ]
