# Generated by Django 2.2.9 on 2020-01-17 15:00

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models

import suministrospr.utils.fields


def migrate_taggit_items(apps, schema_editor):
    Taggit = apps.get_model("taggit", "Tag")
    TaggedItem = apps.get_model("taggit", "TaggedItem")
    Tag = apps.get_model("suministros", "Tag")
    Suministro = apps.get_model("suministros", "Suministro")

    for tag in Taggit.objects.all():
        created_tag = Tag.objects.create(name=tag.name)

        for item in TaggedItem.objects.filter(tag=tag):
            suministro = Suministro.objects.get(pk=item.object_id)
            suministro.tags.add(created_tag)


class Migration(migrations.Migration):

    dependencies = [
        ("suministros", "0005_auto_20200115_2301"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    suministrospr.utils.fields.DateTimeCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified_at",
                    suministrospr.utils.fields.DateTimeModifiedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        populate_from=["name"],
                    ),
                ),
            ],
            options={
                "ordering": ("-modified_at", "-created_at"),
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="suministro",
            name="tags",
            field=models.ManyToManyField(blank=True, to="suministros.Tag"),
        ),
        migrations.RunPython(migrate_taggit_items),
    ]
