# Generated by Django 2.2.9 on 2020-01-15 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suministros", "0005_auto_20200115_1731"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suministro",
            name="created_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
