# Generated by Django 2.2.9 on 2020-01-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0006_auto_20200116_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suministro',
            options={'verbose_name': 'suministro', 'verbose_name_plural': 'suministros'},
        ),
        migrations.AddIndex(
            model_name='suministro',
            index=models.Index(fields=['title'], name='suministros_title_dfc01c_idx'),
        ),
    ]
