# Generated by Django 2.2.9 on 2020-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suministros", "0007_auto_20200116_0218"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="suministro",
            index=models.Index(fields=["title"], name="suministros_title_dfc01c_idx"),
        ),
    ]
