# Generated by Django 2.2.9 on 2020-01-17 23:13

from django.db import migrations

from ..constants import MUNICIPALITIES

def create_municipalities(apps, schema_editor):
    Municipality = apps.get_model("suministros", "Municipality")

    for muncipality_name in MUNICIPALITIES.values():
        Municipality.objects.create(name=muncipality_name)



class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0008_auto_20200117_2312'),
    ]

    operations = [
        migrations.RunPython(create_municipalities),
    ]

