# Generated by Django 2.2.9 on 2020-01-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0008_auto_20200116_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministro',
            name='municipality_fk',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suministros.Municipality'),
        ),
    ]
