# Generated by Django 2.2.9 on 2020-01-17 23:15

from django.db import migrations, transaction

def copy_municipality_data_to_new_column(apps, schema_editor):
    Suministro = apps.get_model("suministros", "Suministro")
    Municipality = apps.get_model("suministros", "Municipality")

    municipality_slug_to_instance_map = dict()

    all_municipalities = Municipality.objects.all()
    for municipality in all_municipalities:
        municipality_slug_to_instance_map[municipality.slug] = municipality

    suministros = Suministro.objects.select_for_update().all()

    with transaction.atomic():
        for suministro in suministros:
            suministro.municipality_fk = municipality_slug_to_instance_map[
                suministro.municipality
            ]
            suministro.save()


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0010_suministro_municipality_fk'),
    ]

    operations = [
        migrations.RunPython(copy_municipality_data_to_new_column),
    ]
