# Generated by Django 2.2.9 on 2020-01-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0010_auto_20200116_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suministro',
            name='municipality',
        ),
    ]
