# Generated by Django 2.2.9 on 2020-01-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0011_auto_20200117_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suministro',
            name='municipality',
        ),
    ]
