repos:
  -   repo: https://github.com/ambv/black
      rev: 19.10b0
      hooks:
      - id: black
        language_version: python3.8
        exclude: .*\/migrations\/.*

  -   repo: https://github.com/asottile/seed-isort-config
      rev: v1.9.4
      hooks:
      - id: seed-isort-config
        exclude: .*\/migrations\/.*

  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
      -   id: isort
          exclude: .*\/migrations\/.*

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
      -   id: flake8
          exclude: .*\/migrations\/.*
