name: Build and test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit checks
      run: pre-commit run --all-files
